spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cushion
    username: root
    password: cushionsql

logging:
    level:
      org.hibernate.SQL: debug