spring:
  application:
    name: cushion

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - email
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - email
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    secret: ${JWT_SECRET}
    token:
      access-expiration-time: 1800000     # 30분
      refresh-expiration-time: 604800000   # 7일

ncp:
  clova:
    studio:
      apiUrl: https://clovastudio.stream.ntruss.com/testapp/v1/chat-completions/HCX-003
      apiKey: NTA0MjU2MWZlZTcxNDJiY7pPd+orksyO1xg/bSt21ETuPj9PtozFgOhLQ61GWxOV
      apiKeyPrimaryVal: 0tlrvnyZ2hx8XxB7cKTNOMy93v21ZxQtxMYOEEFU
      requestId: ce8edcbc-3520-47f2-8b7e-9667457dc114
    ocr:
      secretKey: a3Rpd3poakRZdnpoVHJJS1BDdFd6S2VVdGxxR0ZRSFA=
      apiUrl: https://o3uw4trf4x.apigw.ntruss.com/custom/v1/32848/d0eae8d194776727906d624ca59b2198d53891780a222e3db043f80e500ee1c6/general

logging:
    level:
      org.hibernate.SQL: debug