spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cushion
    username: root
    password: ${DEV_MYSQL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://223.130.132.182:8080/login/oauth2/code/google
          naver:
            redirect-uri: http://223.130.132.182:8080/login/oauth2/code/naver
          kakao:
            redirect-uri: http://223.130.132.182:8080/login/oauth2/code/kakao

logging:
    level:
      org.hibernate.SQL: debug
