spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cushion
    username: root
    password: ${DEV_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://api.coocian.com/login/oauth2/code/google
          naver:
            redirect-uri: https://api.coocian.com/login/oauth2/code/naver
          kakao:
            redirect-uri: https://api.coocian.com/login/oauth2/code/kakao

logging:
    level:
      org.hibernate.SQL: debug

oauth2:
  success:
    redirect-url-new: https://www.coocian.com/cushion # TODO : 프론트 도메인 연결시 변경
    redirect-url-existing: https://www.coocian.com/chat-list/